<?php
// $Id$ 

/**
 * @file Drupal module for MoTag research project
 */

///**
// * Implementation of hook_block()
// */
//function WebNAPTR_block($op='list', $delta=0, $edit=array()) {
//  switch ($op) {
//    case 'list':
//
//    case 'view':
//
//    case 'configure':
//
//    case 'save':
//
//  }
//}

/**
 * Implementation of hook_menu()
 */
function MoTag_menu() {
   $items = array();

   $items['start_research'] = array(
           'title' 		=> 'Start test',
           'access callback' 	=> 'user_access',
           'access arguments' 	=> array('motag_add'),
           'page callback' 	=> 'drupal_get_form',
           'page arguments' 	=> array('MoTag_test_start'),
           'type' 		=> MENU_NORMAL_ITEM,
           'file' => 'MoTag_add.inc',

           'weight' => 3,
   );

   $items['finish'] = array(
           'title' 		=> 'Finish test',
           'access callback' 	=> 'user_access',
           'access arguments' 	=> array('motag_add'),
           'page callback' 	=> 'drupal_get_form',
           'page arguments' 	=> array('MoTag_finish'),
           'type' 		=> MENU_NORMAL_ITEM,
           'file' => 'MoTag_finish.inc',

           'weight' => 4,
   );

   $items['show_pending'] = array(
           'title' 		=> 'Show pending tests',
           'access callback' 	=> 'user_access',
           'access arguments' 	=> array('motag_browse'),
           'page callback' 	=> 'MoTag_show',
           'page arguments' 	=> array('1'),
           'type' 		=> MENU_NORMAL_ITEM,
           'file' => 'MoTag_show.inc',

           'weight' => 5,
   );

   $items['show_finished'] = array(
           'title' 		=> 'Show finished tests',
           'access callback' 	=> 'user_access',
           'access arguments' 	=> array('motag_browse'),
           'page callback' 	=> 'MoTag_show',
           'page arguments' 	=> array('0'),
           'type' 		=> MENU_NORMAL_ITEM,
           'file' => 'MoTag_show.inc',

           'weight' => 6,
   );

   /*$items['reload'] = array(
           'title' 		=> 'Reload motag module',
           'access callback' 	=> 'user_access',
           'access arguments' 	=> array('motag_add'),
           'page callback' 	=> 'motag_reload',
           'type' 		=> MENU_NORMAL_ITEM,
           'file' => 'MoTag.install',

           'weight' => 10,
   );*/

   return $items;
}

/**
 * Implements hook_permission().
 */
function MoTag_permission() {
   return array(
           'motag_add' => array(
                   'title' 		=> t('Add experiments'),
                   'description' 	=> t('Add experiments to the system.'),
           ),
           'motag_browse' => array(
                   'title' 		=> t('Browse experiments'),
                   'description' 	=> t('Browse through experiments in the system.'),
           ),
   );
}


///**
// * Implementation of hook_help()
// */
//function WebNAPTR_help($path, $arg) {
//
//}
